skip_tags: true

os: Visual Studio 2015

environment:
  matrix:
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python37-x64"
    # The Windows Python 3.8 tests currently fail on
    # test_asyncio.test_windows_events.ProactorLoopCtrlC where `get_event_loop`
    # fails to start a new loop
    # https://ci.appveyor.com/project/smurfix/trio-asyncio/builds/33592418/job/06yddkw8wy9y6j1h
    # - PYTHON: "C:\\Python38"
    # - PYTHON: "C:\\Python38-x64"

build_script:
  - "git --no-pager log -n2"
  - "echo %APPVEYOR_REPO_COMMIT%"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;;%PATH%"
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "pip install ."
  - "pip install -Ur ci/test-requirements.txt"
  - "pip install codecov"

test_script:
  - "mkdir empty"
  - "cd empty"
  # Make sure it's being imported from where we expect
  - "python -c \"import os, trio_asyncio; print(os.path.dirname(trio_asyncio.__file__))\""
  - "python -u -m pytest -ra -v -s --cov=trio_asyncio --cov-config=../.coveragerc ../tests"
  - "codecov"
